//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complejo_Deportivo
    {
        public decimal idComplejoDeportivo { get; set; }
        public string cmdNombre { get; set; }
        public string cmdDireccion { get; set; }
        public string cmdFono { get; set; }
        public string cmdCelular { get; set; }
        public string cmdFax { get; set; }
        public string cmdEmail { get; set; }
        public string cmdGeoreferencia { get; set; }
        public string cmdUrl { get; set; }
        public Nullable<System.DateTime> cmdCreacion { get; set; }
    }
}
