//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deporte
    {
        public decimal idDeporte { get; set; }
        public string depNombre { get; set; }
        public Nullable<decimal> depFamilia { get; set; }
        public Nullable<System.DateTime> depCreacion { get; set; }
    }
}
