//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_Invitacion
    {
        public decimal idEquipoInvitacion { get; set; }
        public Nullable<decimal> idEquipo { get; set; }
        public Nullable<decimal> idJugador { get; set; }
        public Nullable<decimal> einEstado { get; set; }
        public Nullable<System.DateTime> einCreacion { get; set; }
        public Nullable<System.DateTime> einModificacion { get; set; }
    }
}
