//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public decimal idEquipo { get; set; }
        public string equNombre { get; set; }
        public string equEscudo { get; set; }
        public string equDescripcion { get; set; }
        public string equUrl { get; set; }
        public string equEmail { get; set; }
        public string equContacto { get; set; }
        public string equContactoFono { get; set; }
        public string equContactoCelular { get; set; }
        public string equContactoEmail { get; set; }
        public Nullable<System.DateTime> equCreacion { get; set; }
    }
}
