//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public decimal idJugador { get; set; }
        public string jugUsername { get; set; }
        public string jugPassword { get; set; }
        public Nullable<decimal> jugRut { get; set; }
        public string jugRutDv { get; set; }
        public string jugNombre { get; set; }
        public string jugPaterno { get; set; }
        public string jugMaterno { get; set; }
        public string jugFono { get; set; }
        public string jugCelular { get; set; }
        public string jugEmail { get; set; }
        public string jugFoto { get; set; }
        public Nullable<System.DateTime> jugCreacion { get; set; }
        public string jugApodo { get; set; }
    }
}
