//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido_Incidente
    {
        public decimal idPartidoIncidente { get; set; }
        public Nullable<decimal> idJugador { get; set; }
        public Nullable<decimal> idPartido { get; set; }
        public Nullable<decimal> pinTarjetaAmarilla { get; set; }
        public Nullable<decimal> pinTarjetaRoja { get; set; }
        public Nullable<decimal> pinGol { get; set; }
        public Nullable<System.DateTime> pinCreacion { get; set; }
    }
}
