//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido_Jugador
    {
        public decimal idPartidoJugador { get; set; }
        public Nullable<decimal> idJugador { get; set; }
        public Nullable<decimal> idPartido { get; set; }
        public Nullable<decimal> pjuGalleta { get; set; }
        public Nullable<decimal> pjuEstado { get; set; }
        public Nullable<System.DateTime> pjuCreacion { get; set; }
    }
}
