//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PichangueaUsachEntities : DbContext
    {
        public PichangueaUsachEntities()
            : base("name=PichangueaUsachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Cancha> Cancha { get; set; }
        public virtual DbSet<Complejo_Deportivo> Complejo_Deportivo { get; set; }
        public virtual DbSet<Deporte> Deporte { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Equipo_Chat> Equipo_Chat { get; set; }
        public virtual DbSet<Equipo_Invitacion> Equipo_Invitacion { get; set; }
        public virtual DbSet<Equipo_Jugador> Equipo_Jugador { get; set; }
        public virtual DbSet<Equipo_Solicita_Ingreso> Equipo_Solicita_Ingreso { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Partido_Chat> Partido_Chat { get; set; }
        public virtual DbSet<Partido_Incidente> Partido_Incidente { get; set; }
        public virtual DbSet<Partido_Jugador> Partido_Jugador { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Cancha> Tipo_Cancha { get; set; }
        public virtual DbSet<Tipo_Partido> Tipo_Partido { get; set; }
    }
}
