//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PichangueaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cancha
    {
        public decimal idTipoCancha { get; set; }
        public Nullable<decimal> idDeporte { get; set; }
        public string tcaNombre { get; set; }
        public Nullable<System.DateTime> tcaCreacion { get; set; }
    }
}
